# アクション名
name: Github Action Test

# タイミングを指定
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
jobs:
  Test:
    name: Run test codes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: repogitory checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
          cache: npm

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build --if-present

      - name: run test
        run: npm run test
