# アクション名
name: GitHub Action Test

# タイミングを指定
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  Test:
    name: Run test codes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      db:
        image: postgres:16.1
        ports:
          - '5433:5432'
        env:
          POSTGRES_USER: bulletin-board
          POSTGRES_PASSWORD: auT*k!K9Tp(8
          POSTGRES_DB: bulletin-board

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Prisma Generate
        run: npx prisma generate

      - name: Prisma Migrate
        env:
          DATABASE_URL: postgresql://bulletin-board:auT*k!K9Tp(8@localhost:5433/bulletin-board
        run: npx prisma migrate dev

      - name: Run tests
        env:
          DATABASE_URL: postgresql://bulletin-board:auT*k!K9Tp(8@localhost:5433/bulletin-board
        run: npm run test
