# アクション名
name: Github Action Test

# タイミングを指定
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  Test:
    name: Run test codes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: echo Hello World
